### ISSUE TITLE
new bug report about Slow Loading Time When Clicking on a Product

### ISSUE THREAD

**Issue by lyhamissi** [yegobox/flipper#319]
Users experience significant delays (10-30 seconds) when clicking on a product to view its details. This issue negatively impacts the user experience, making the app load slowly and led to inefficient user experience .
Expected Result:
The product details page should load within 1-2 seconds after clicking on the product, providing a smooth and responsive user experience.
Actual Result:
The product details page takes 10-30 seconds to load after clicking on the product, causing delays and a poor user experience.

**Comment by richard457** [comment]
Are you doing a Long press on a product?  @lyhamissi

**Comment by lyhamissi** [comment]
when I click to the product it takes up time to be viewed

**Comment by richard457** [comment]
I'm not sure I understand where you want to see the product, maybe you include a screenshot with where you want to see it, etc... as far as I know you can click on a product to either sale it on Basket or long press to edit/ delete
