### ISSUE TITLE
Paid Account Not Recognized Across Devices

### ISSUE THREAD

**Issue by lyhamissi** [yegobox/flipper#326]
I encountered an issue where, after purchasing a subscription to your app on one device, the payment is not recognized when I log in on another device using the same account. The account shows that I haven't paid, even though the payment was processed successfully and the service was activated on the original device.

**Comment by richard457** [comment]
@lyhamissi This is fixed in the latest release please check

**Comment by richard457** [comment]
https://github.com/yegobox/flipper/actions/runs/10689641340
