### ISSUE TITLE
Improve the login form field

### ISSUE THREAD

**Issue by richard457** [yegobox/flipper#43]
We need to add a country code from form-field so the country code can be auto-field.

**Comment by richard457** [comment]
@tuganimana the field still accepts the +250 for example before a number while the country code is pre-filled, would be nice if a user writes +250 in the field to automatically remote it for example +2507834... would become 7834 as +250 would be automatically added by the chosen country code.

**Comment by tuganimana** [comment]
The code are generated on click or onInit, I think? I don't get well what's not working ?  I have to send +250783.... ?

**Comment by tuganimana** [comment]
I think that is what i am sending ? But will check it and see

**Comment by richard457** [comment]
This has been fixed.
