### ISSUE TITLE
Selling a produdct's Variant (UI only)

### ISSUE THREAD

**Issue by richard457** [yegobox/flipper#48]
**UI IMPLEMENTATION**
**No Logic Required** Just mock required data and return them from **ProductsViewModel** (this model exist)

1. On click of the item with no variants (variable item or item with no price set) it should take you to a calculator where you enter the price for the item to sell
2. On click of the item with price or item with more than once variant it should take you to a screen where you can increment the quantity of every single item, Let's use **ProductsViewModel** (this model exist) and **SharedStateService** in case we need to share state

**LOGIC**

**Now we can add product and their related variant or variants**

- A variant has a stock
- A Variant is associated with one product
- A product belongs to a branch and business.
**Now we need to sell this variant from a stock**
Follow Square mobile app about how they do it, it is already done but it has a bug in it.

-> **This is the flow on desktop**

1. At the start of selling we create a draft order i.e an Order where a status property is a draft.
2. Created orderDetail
3. Check if calculation is okay
4. Save Order change status to Complete and draft property to false

**Comment by gannza** [comment]
public async newOrder() {
    if (!this.currentOrder) {
          const formOrder:Order={
                id: this.database.uid(),
                reference: 'SO' + this.generateCode(),
                orderNumber: 'SO' + this.generateCode(),
                branchId: this.defaultBranch ? this.defaultBranch.id : '0',
                status: STATUS.OPEN,
                orderType: ORDERTYPE.SALES,
                active: true,
                orderItems: [],
                isDraft: true,
                subTotal: 0.00,
                cashReceived: 0.00,
                customerChangeDue: 0.00,
                table: 'orders',
                channels:[this.defaultBusiness$.userId],
                createdAt: this.date,
                updatedAt: this.date
          };

      await this.database.put(PouchConfig.Tables.orders + '_' + formOrder.id, formOrder);
      this.hasDraftOrder();

    }

  }

**Comment by gannza** [comment]
Function for creating a new order on start pos or on complete the draft order.

**Comment by gannza** [comment]
taxRate = event.tax?event.tax:tax ? tax : 0;

    const orderDetails: OrderDetails = {
      id: this.database.uid(),
      price: variant.priceVariant.retailPrice,
      variantName: variant.name,
      productName: variant.productName,
      canTrackStock: variant.stock.canTrackingStock,
      stockId: variant.stock.id,
      unit: variant.unit,
      SKU: variant.SKU,
      quantity: event.quantity,
      variantId: variant.id,
      taxRate,
      taxAmount: ((variant.priceVariant.retailPrice * event.quantity) * taxRate) / 100,
      orderId: this.currentOrder.id,
      subTotal: variant.priceVariant.retailPrice * event.quantity,
      table:'orderDetails',
      createdAt: this.date,
      updatedAt: this.date,
      channels:[this.defaultBusiness$.userId]
    };

    this.database.put(PouchConfig.Tables.orderDetails +'_'+ orderDetails.id, orderDetails);

to add the item to the cart, we save data in orderDetails like the above model

**Comment by gannza** [comment]
async didCollectCash(event) {
    this.collectCashCompleted = { isCompleted: false, collectedOrder: this.currentOrder };
    if (event === true) {
      await this.allOrderDetails(this.currentOrder.id);
      await this.createStockHistory();
      this.currentOrder.isDraft = false;
      this.currentOrder.active = false;
      this.currentOrder.status = STATUS.COMPLETE;
       this.currentOrder.createdAt = new Date().toISOString();
       this.currentOrder.updatedAt = new Date().toISOString();
       this.currentOrder.customerChangeDue=this.currentOrder.customerChangeDue;
      
      
   

      await this.database.put(PouchConfig.Tables.orders + '_' +  this.currentOrder.id,  this.currentOrder);

      
      this.collectCashCompleted = { isCompleted: true, collectedOrder: this.currentOrder };
      this.currentOrder = null;
      await this.init();

    }
on CollectCash we have to update the draft order

**Comment by richard457** [comment]
> ` public async newOrder() {`
> 
> > `if (!this.currentOrder) {`
> > `const formOrder:Order={`
> > `id: this.database.uid(),`
> > `reference: 'SO' + this.generateCode(),`
> > `orderNumber: 'SO' + this.generateCode(),`
> > `branchId: this.defaultBranch ? this.defaultBranch.id : '0',`
> > `status: STATUS.OPEN,`
> > `orderType: ORDERTYPE.SALES,`
> > `active: true,`
> > `orderItems: [],`
> > ` isDraft: true,`
> > `subTotal: 0.00,`
> > `cashReceived: 0.00,`
> > `customerChangeDue: 0.00,`
> > `table: 'orders',`
> > `channels:[this.defaultBusiness$.userId],`
> > `createdAt: this.date,`
> > ` updatedAt: this.date`
> 
> ```
>       };
> 
>   await this.database.put(PouchConfig.Tables.orders + '_' + formOrder.id, formOrder);
>   this.hasDraftOrder();
> 
> }
> ```
> 
> }

Did I get the flow right?
